config/routes.rb
Rails.application.routes.draw do
  resources :classifieds
  resources :markets
 
  resources :businesses

  resource :session, only:[:new, :create, :destroy]
  resources :user_signed_in
  resources :users, only: [:new, :create, :show]

  # Defines the root path route ("/")
  root "businesses#index"

  resources :business do
    resources :likes, shallow: true, only: [:create, :destroy]
  end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only:[:show, :edit, :update, :destroy]

  before_action :authenticate_user!, except: [:index, :show]

  before_action :authorize_user!, only:[:edit, :update, :destroy]

  # GET /businesses or /businesses.json
  def index
    # @businesses = Business.all
    #  @likes = Like.group(:business_id)
     @likes = Like.group(:business_id).count(:id)
    #  @likes = Like.group(:businesses).count
    @spotlight = Business.offset(rand(Business.count - 3)).limit(3)
    # @q = Business.all.joins(:likes).count(:business_id)
   
    #TESTING FOR LIKES:
  #  @q = Business.select("businesses.*,count(likes.*) AS likes").joins("INNER JOIN likes ON business_id = likes.business_id").group("likes.business_id")

        
  
        # @businesses = Business.all

        #before:
        @q = Business.ransack(params[:q])
        @businesses = @q.result(distinct: true)
      

    

  end

  # GET /businesses/1 or /businesses/1.json
  def show
    # @likes = @business.likes.find_by(user: current_user)
    @like = @business.likes.find_by(user: current_user)
    p @business.id
  end

  # GET /businesses/new
  def new
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses or /businesses.json
  def create
    @business = Business.new(business_params)
    @business.user = current_user

    respond_to do |format|
      if @business.save
        format.html { redirect_to business_url(@business), notice: "Business was successfully created." }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /businesses/1 or /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to business_url(@business), notice: "Business was successfully updated." }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1 or /businesses/1.json
  def destroy
    @business.destroy

    respond_to do |format|
      format.html { redirect_to businesses_url, notice: "Business was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def liked
    @businesses = current_user.liked_businesses
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      p "******************* set business method before"
      p params
      @business = Business.find(params[:id])

      p "******************* set business method after"

    end

    # Only allow a list of trusted parameters through.
    def business_params
      params.require(:business).permit(:business_name, :category, :one_liner, :business_email, :business_phone, :description, :logo_url, :shop_online, :website)
    end

    def authorize_user!
      redirect_to root_path, alert: "Not authorized!" unless can?(:crud, @business)
    end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_business.html.erb
<div id="<%= dom_id business %>">
  <p>
    <strong>Business name:</strong>
    <%= business.business_name %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= business.category %>
  </p>

  <p>
    <strong>One liner:</strong>
    <%= business.one_liner %>
  </p>

  <p>
    <strong>Business email:</strong>
    <%= business.business_email %>
  </p>

  <p>
    <strong>Business phone:</strong>
    <%= business.business_phone %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= business.description %>
  </p>

  <p>
    <strong>Logo url:</strong>
    <%= business.logo_url %>
  </p>

  <p>
    <strong>Shop online:</strong>
    <%= business.shop_online %>
  </p>

  <p>
    <strong>Website:</strong>
    <%= business.website %>
  </p>

</div>

app/views/businesses/_form.html.erb
<%= form_with(model: business) do |form| %>
  <% if business.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
        <% business.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  </div>

  <div>
    <%= form.label :business_name, style: "display: block" %>
    <%= form.text_field :business_name, placeholder: "LOJO Undies" %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.select :category, ['Skincare','Furniture','Leatherwork','Clothing','Food','Other'] %>
  </div>

<div>
    <%= form.label :one_liner, style: "display: block" %>
    <%= form.text_field :one_liner, placeholder: "Breathable Undies, design, cut, and sewn in BC!" %>
  </div>

  <div>
    <%= form.label :business_email, style: "display: block" %>
    <%= form.text_field :business_email, placeholder: "info@lojoundies.com" %>
  </div>

  <div>
    <%= form.label :business_phone, style: "display: block" %>
    <%= form.text_field :business_phone, placeholder: "250-867-5309" %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, placeholder: "Enter a longer description, origins, mission, etc" %>
  </div>

  <div>
    <%= form.label :logo_url, style: "display: block" %>
    <%= form.text_field :logo_url, placeholder: "https://cdn.shopify.com/s/files/1/0601/1122/5029/files/LOGO-LOJO-01_180x.png?v=1636309319" %>
  </div>

  <div>
    <%= form.label :spotlight_photo, style: "display: block" %>
    <%= form.text_field :spotlight_photo, placeholder:"Link your fave product photo" %>
  </div>

  <div>
    <%= form.label :shop_online, style: "display: block" %>
    <%= form.check_box :shop_online %>
  </div>

  <div>
    <%= form.label :website, style: "display: block" %>
    <%= form.text_field :website, placeholder: "lojoundies.com/shop" %>
  </div>

  <div>
    <%= form.submit class:"btn btn-dark" %>
  </div>
<% end %>

app/views/businesses/_spotlight.html.erb
<div class="jumbotron">
  <h1 class="display-5">Spotlight on: <strong><span class="text-secondary"><%= @spotlight.first.business_name %> </span></strong> </h1>
  <div class="container-sm clearfix">
  
  <% if (@spotlight.first.spotlight_photo) %>
  <img class="card-img-top col-md-6 float-md-start mb-3 ms-md-3 mx-3" src="<%= @spotlight.first.spotlight_photo %>"
style="max-width:300px" alt="Card image cap">
<% else %>
 <img class="card-img-top col-md-6 float-md-start mb-3 ms-md-3 mx-3" src="<%= @spotlight.first.logo_url %>"
style="max-width:300px" alt="Card image cap">
<% end %>



<div class="container justify-center">
<div class="container">
  <p class="lead "><%= @spotlight.first.description.truncate(300) %></p>
     <%= link_to "Learn More", @spotlight.first, class:"btn btn-dark btn-lg" %>
    </div>
 </div>   
</div>
  <hr class="my-4">
 
</div>
<br />
<br />
<br />

app/views/businesses/edit.html.erb
<div class="container">
<h1>Editing business</h1>

<%= render "form", business: @business %>

<br>

<div>
  <%= link_to "Show this business", @business %> |
  <%= link_to "Back to businesses", businesses_path %>
</div>
</div>

app/views/businesses/index.html.erb
<div class="container">

<% if %>
<%= render "spotlight", business: @business %>
<% end %>


<h1>Nanaimo Businesses</h1>
<%= search_form_for @q do |f| %>
  <% f.label :business_name_or_description_or_category_cont %>
  <%= f.search_field :business_name_or_description_or_category_cont %>
  <%= f.submit class: "btn btn-dark btn-sm" %>
<% end %>
<br />
  <span> Sort by:  </span>
    <span><%= sort_link(@q, :category, "Category", default_order: :asc, class: "btn btn-dark btn-sm") %></span> <span> |  </span>
     <span><%= sort_link(@q, :business_name, "Alphabetical", default_order: :asc, class: "btn btn-dark btn-sm") %> </span>
     <span> |  </span> 
     <span><%= sort_link(@q, :likes, "Number of Likes", default_order: :asc, class: "btn btn-dark btn-sm") %></span>
  <hr />
<div class="businesses container-fluid ">

<br />
    <div class="row row-cols-12 row-cols-md-6 row-cols-lg-4 justify-content-center">
        <% @businesses.each do |business| %>
      <div class="card text-center" style="width: 18rem;">
      <div class="badge bg-secondary text-wrap text-uppercase" style="width: 6rem, justify-end">
         <%=business.category%>
      </div>
       <img class="card-img-top img-thumbnail" src="<%= business.logo_url %>" width="25px"alt="Card image cap">
  <div class="container">
      <div class="card-body">
        <h5 class="card-title"><%= business.business_name %></h5>
        <p class="card-text"> <%=business.one_liner%> <p> <strong>Liked by:</strong> <%= business.likes.count %> </p>
          <%= link_to "More info", business, class:"btn btn-dark", style:"justify-bottom;" %>
      </div>
  </div>
  </div>
      
    <% end %>
  </div>
  </div>
</div>

app/views/businesses/new.html.erb
<div class="container">
<h1>Add your business to the directory!</h1>

<%= render "form", business: @business %>

<br>

</div>

app/views/businesses/show.html.erb
<div class="container">
  <div class="badge bg-secondary text-wrap text-uppercase" style="width: 9rem;">
      <%=@business.category%>
      <br />
  </div>
  <div class="container text-center">
    <% if(@business.logo_url)%>
      <img src="<%=@business.logo_url%>" width="300" >
      <br />
      <br />
    <% end%>
<h1 class="text-secondary"><strong> <%=  @business.business_name %> </strong></h1>
<small> Business Owner:  <%= @business.user.full_name  %> </small>
<% if (@business.likes.count > 0) %>
<br />
 <small>Liked by: <%= @business.likes.count %> users</small>
 
<% end %>
  </div>
<div class ="container mt-5 text-left">
<div class="container">
<small>
  <% if @like.present? %>
      <%= button_to "Liked ✔️", like_path(@like), method: :delete, class: 'btn btn-outline-secondary btn-sm' %>
    <% else %>
      <%= button_to "👍 Like", business_likes_path(@business), method: :post, class: 'btn btn-outline-primary' %>
    <% end %>
</small>
</div>
 


<div class="container">
  <div>
    <div>
 
  
<br />
<br />

    </div>
    
    <div class="shadow p-3 mb-5 bg-bodyrounded"> 
    <strong>More about <span class="text-capitalize"><%= @business.business_name  %> </span> <br /> <br /> </strong> <%= @business.description %>
    
    <div class="text-capitalize"> <br /> <strong>Category:</strong> <%= @business.category %></div>
    <div class="text-capitalize"> <br /> <strong>One-liner:</strong> <%= @business.one_liner %></div>
    <div class="text-lowercase"> <br /> <strong>Email:</strong> <%= @business.business_email %></div>
    <div> <br /> <strong>Phone:</strong> <%= @business.business_phone %></div>
    </div>
  </div>
</div>



  <% if (@business.shop_online)  %>
  <%= link_to 'Shop Online', (@business.website), class: 'btn btn-dark' %>
  <%  else %>
  <p> Contact to Order </p>
  <%  end %>


<br />
<br />

</div>




<div>
<% if can? :crud, @business %>
  <%= link_to "Edit this Business", edit_business_path(@business), class: 'btn btn-outline-dark' %> 
<% end %>
<% if current_user == @business.user %>
  <%= button_to "Delete this business", @business, method: :delete, class: 'btn btn-outline-danger' %>
<%end %>
</div>