config/routes.rb
Rails.application.routes.draw do
  resources :classifieds
  resources :markets
 
  resources :businesses

  resource :session, only:[:new, :create, :destroy]
  resources :user_signed_in
  resources :users, only: [:new, :create, :show]

  # Defines the root path route ("/")
  root "businesses#index"

  resources :business do
    resources :likes, shallow: true, only: [:create, :destroy]
  end
end

app/models/classified.rb
class Classified < ApplicationRecord
    belongs_to :user
end

app/controllers/classifieds_controller.rb
class ClassifiedsController < ApplicationController
  before_action :set_classified, only: %i[ show edit update destroy ]

  before_action :authenticate_user!, except: [:index, :show]

  before_action :authorize_user!, only:[:edit, :update, :destroy]

  # GET /classifieds or /classifieds.json
  def index
    # @classifieds = Classified.all

    #  @keyword = params[:q].values[0]
      @q = Classified.ransack(params[:q])
      @classifieds = @q.result(distinct: true)
  end

  # GET /classifieds/1 or /classifieds/1.json
  def show
  end

  # GET /classifieds/new
  def new
    @classified = Classified.new
  end

  # GET /classifieds/1/edit
  def edit
  end

  # POST /classifieds or /classifieds.json
  def create
    @classified = Classified.new(classified_params)
    @classified.user = current_user

    respond_to do |format|
      if @classified.save
        format.html { redirect_to classified_url(@classified), notice: "Classified was successfully created." }
        format.json { render :show, status: :created, location: @classified }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @classified.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classifieds/1 or /classifieds/1.json
  def update
    respond_to do |format|
      if @classified.update(classified_params)
        format.html { redirect_to classified_url(@classified), notice: "Classified was successfully updated." }
        format.json { render :show, status: :ok, location: @classified }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @classified.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classifieds/1 or /classifieds/1.json
  def destroy
    @classified.destroy

    respond_to do |format|
      format.html { redirect_to classifieds_url, notice: "Classified was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classified
      @classified = Classified.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def classified_params
      params.require(:classified).permit(:title, :category, :contact_info, :image_url, :description)
    end

    def authorize_user!
      redirect_to root_path, alert: "Not authorized!" unless can?(:crud, @classified)
    end
end

app/helpers/classifieds_helper.rb
module ClassifiedsHelper
end

app/views/classifieds/_classified.html.erb
<div id="<%= dom_id classified %>">
  <p>
    <strong>Title:</strong>
    <%= classified.title %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= classified.category %>
  </p>

  <p>
    <strong>Contact info:</strong>
    <%= classified.contact_info %>
  </p>

  <p>
    <strong>Image url:</strong>
    <%= classified.image_url %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= classified.description %>
  </p>

</div>

app/views/classifieds/_form.html.erb
<%= form_with(model: classified) do |form| %>
  <% if classified.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(classified.errors.count, "error") %> prohibited this classified from being saved:</h2>

      <ul>
        <% classified.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

 <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.select :category, ['Paid Job','Paid Gig','Volunteer Position','Buy','Sell','Contest Collaboration' , 'Other'] %>
  </div>

  <div>
    <%= form.label :contact_info, style: "display: block" %>
    <%= form.text_field :contact_info %>
  </div>

  <div>
    <%= form.label :image_url, style: "display: block" %>
    <%= form.text_field :image_url %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit class: "btn btn-dark" %>
  </div>
<% end %>

app/views/classifieds/edit.html.erb
<h1>Editing classified</h1>

<%= render "form", classified: @classified %>

<br>

<div>
  <%= link_to "Show this classified", @classified %> |
  <%= link_to "Back to classifieds", classifieds_path %>
</div>

app/views/classifieds/index.html.erb
<div class="container">
<h1>Classifieds</h1>


<%= search_form_for @q do |f| %>

  <% f.label :title_or_description_or_category_cont %>
  <%= f.search_field :title_or_description_or_category_cont %>
  <%= f.submit class: 'btn btn-dark' %>
<% end %>



  <span> Sort by:  </span>
    <span><%= sort_link(@q, :category, "Category", default_order: :asc) %></span> <span> |  </span>
     <span><%= sort_link(@q, :title, "Alphabetical", default_order: :asc) %> </span>
  
  <hr />




<div class="classfieds container-fluid ">
  <div class="row row-cols-12 row-cols-md-6 row-cols-lg-4 justify-content-center">
  <% @classifieds.each do |classified| %>
    

    <div class="card text-center" style="width: 18rem;">
      <div class="badge bg-secondary text-wrap text-uppercase" style="width: 9rem;">
         <%=classified.category%>
      </div>

    <% if (classified.image_url) %>
  <img class="card-img-top img-thumbnail" src="<%= classified.image_url %>" width="25px"alt="Card image cap">
  <% end %>

  <div class="card-body">
     <h5 class="card-title"><%= classified.title %></h5>
   
    <p class="card-text"> <%=classified.description.truncate(200)%> </p>

      <%= link_to "View this ad", classified, class:"btn btn-outline-dark" %>
  </div>
</div>
    
  <% end %>
</div>
</div>
</div>

app/views/classifieds/new.html.erb
<h1>New classified</h1>

<%= render "form", classified: @classified %>

<br>

<div>
  <%= link_to "Back to classifieds", classifieds_path %>
</div>

app/views/classifieds/show.html.erb
<div class="container">
<div class ="container mt-5 text-left">
<br />

<h3> <%= @classified.title  %> </h3>
<small> Posted by:  <%= @classified.user.full_name  %> </small>
  <br />
  <br />
  <div class="badge bg-secondary text-wrap text-uppercase" style="width: 9rem;">
      <%=@classified.category%>
  </div>
<br />



<% if(@classified.image_url)%>
  <img src="<%=@classified.image_url%>" width="200">
  <br />
  <br />
<% end%>


 


<div class="container">
  <div>
    <div>
 
  
<br />
<br />

    </div>
    <div class="shadow p-3 mb-5 bg-body rounded"> <%= @classified.description %> --
  <%=@classified.user.first_name%>
    
    <div> <strong>To reply to this ad:</strong> <%= @classified.contact_info %></div>
    </div>
  </div>
</div>


<div>
<br />
<br />
  <%= link_to "Back to Classifieds", classifieds_path, class: "btn btn-dark" %>
<br />
<br />
</div>

<div>
  <% if can? :crud, @classified %>
    <%= link_to "Edit this Ad", edit_classified_path(@classified), class: 'btn btn-outline-dark' %> 
  <% end %>
  <% if current_user == @classified.user %>
    <%= button_to "Delete this Ad", @classified, method: :delete, class: 'btn btn-outline-danger' %>
  <%end %>
</div>