config/routes.rb
Rails.application.routes.draw do
  resources :classifieds
  resources :markets
 
  resources :businesses

  resource :session, only:[:new, :create, :destroy]
  resources :user_signed_in
  resources :users, only: [:new, :create, :show]

  # Defines the root path route ("/")
  root "businesses#index"

  resources :business do
    resources :likes, shallow: true, only: [:create, :destroy]
  end
end

app/models/market.rb
class Market < ApplicationRecord
 belongs_to :user
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  before_action :set_market, only: %i[ show edit update destroy ]

  before_action :authenticate_user!, except: [:index, :show]

  before_action :authorize_user!, only:[:edit, :update, :destroy]

  # GET /markets or /markets.json
  def index
    # @markets = Market.all
    @markets = Market.where(
      start_time: Time.now.beginning_of_month.beginning_of_week..Time.now.end_of_month.end_of_week
    )
  end

  # GET /markets/1 or /markets/1.json
  def show
  end

  # GET /markets/new
  def new
    @market = Market.new
  end

  # GET /markets/1/edit
  def edit
  end

  # POST /markets or /markets.json
  def create
    @market = Market.new(market_params)
    @market.user = current_user

    p @market
    p @market.user

    respond_to do |format|
      if @market.save
        format.html { redirect_to market_url(@market), notice: "Market was successfully created." }
        format.json { render :show, status: :created, location: @market }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @market.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /markets/1 or /markets/1.json
  def update
    respond_to do |format|
      if @market.update(market_params)
        format.html { redirect_to market_url(@market), notice: "Market was successfully updated." }
        format.json { render :show, status: :ok, location: @market }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @market.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /markets/1 or /markets/1.json
  def destroy
    @market.destroy

    respond_to do |format|
      format.html { redirect_to markets_url, notice: "Market was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_market
      @market = Market.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def market_params
      params.require(:market).permit(:title, :description, :address, :start_time, :end_time)
    end

    def authorize_user!
      redirect_to root_path, alert: "Not authorized!" unless can?(:crud, @market)
    end
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/views/markets/_form.html.erb
<%= form_with(model: market) do |form| %>
  <% if market.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(market.errors.count, "error") %> prohibited this market from being saved:</h2>

      <ul>
        <% market.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_area :address %>
  </div>

  <div>
    <%= form.label :start_time, style: "display: block" %>
    <%= form.datetime_field :start_time %>
  </div>

  <div>
    <%= form.label :end_time, style: "display: block" %>
    <%= form.datetime_field :end_time %>
  </div>

  <div>
  <br />
    <%= form.submit class:"btn btn-dark" %>
  </div>
<% end %>

app/views/markets/_market.html.erb
<div id="<%= dom_id market %>">
  <p>
    <strong>Title:</strong>
    <%= market.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= market.description %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= market.address %>
  </p>

  <p>
    <strong>Start time:</strong>
    <%= market.start_time %>
  </p>

  <p>
    <strong>End time:</strong>
    <%= market.end_time %>
  </p>

</div>

app/views/markets/edit.html.erb
<div class="container">
<h1>Editing market</h1>

<%= render "form", market: @market %>

<br>

<div>
  <%= link_to "Show this market", @market class:"btn btn-dark %> |
  <%= link_to "Back to markets", markets_path class:"btn btn-dark %>
</div>
</div>

app/views/markets/index.html.erb
<div class="container">

  <h1>Upcoming Markets</h1>

  <br />
 <br />
  <small> Check out the calendar below for upcoming farmers markets, craft fairs, and more! </small>
<br />
<br />
<%= month_calendar(events: @markets) do |date, markets| %>
  <%= date.day %>

  <% markets.each do |market| %>
    <div>
      <%= link_to market.title, market, class: 'btn btn-outline-dark btn-sm' %>
    </div>
  <% end %>
<% end %>
</div>

app/views/markets/new.html.erb
<div class="container">
<h1>New market</h1>

<%= render "form", market: @market %>

<br>

<div>
  <%= link_to "Back to markets", markets_path,  class:"btn btn-dark" %>
</div>
</div>

app/views/markets/show.html.erb
<h3><%= @market.title %> </h3>

<br />
<strong>About this market </strong><br /><%= @market.description %>
<br />
<br />
<br />


<div class="container clearfix border">
  <div class="row">
    <div class="col-4">

  <ul class="list-group list-group-flush">
  <li class="list-group-item"><strong>Starts: </strong> <%= @market.start_time.strftime('%A, %B %d, %Y at %I:%M %p') %> PST</li>
  <li class="list-group-item"><strong>Ends: </strong> <%= @market.end_time.strftime('%A, %B %d, %Y at %I:%M %p') %> PST</li>

  <li class="list-group-item"><strong>Address: </strong><%= @market.address %></li>
</ul>


    </div>
    <div class="col-8"><img src="https://tourismnanaimo.com/app/uploads/2018/03/map1.jpg" width="600"></div>

  </div>
</div>






<div>
  <%= link_to "Back to markets", markets_path, class: 'btn btn-dark'  %>

   <% button_to "Destroy this market", @market, method: :delete%>
  <% link_to "Edit this market", edit_market_path(@market) %> 
</div>