config/routes.rb
Rails.application.routes.draw do
  resources :classifieds
  resources :markets
 
  resources :businesses

  resource :session, only:[:new, :create, :destroy]
  resources :user_signed_in
  resources :users, only: [:new, :create, :show]

  # Defines the root path route ("/")
  root "businesses#index"

  resources :business do
    resources :likes, shallow: true, only: [:create, :destroy]
  end
end

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/_footer.html.erb
<footer class="bg-secondary">
         
            <div class="row d-flex justify-content-center text-center p-2">
                <div class="col-lg-3 col-md-6 col-sm-12">
                            <%= image_tag "https://cdn-icons-png.flaticon.com/512/3859/3859602.png", id: 'logo-footer', class: "mt-3", style:"width: 3rem"%> 
                    <h2 class="text-light fw-bold mt-3">Nanaimo Makers</h2>
                    
                </div>
            </div>

            <div class="container p-4">

            <div class="row">
                    <div class="col-lg-3 col-md-6 col-sm-12 text-light">
                        <h4 class="mt-3 text-light fw-bold">Contact Us</h1>
                        <p class="text-light">Nanaimo, BC.</p>
                        <p><a class="text-light" href="mailto:kasandradarwin@gmail.com">hello@nanaimomakers.ca</a></p>
                        <p><a class="text-light" href="tel:1-800-888-8888">1-800-888-8888</a></p>
                    </div>

                    <div class="col-lg-3 col-md-6 col-sm-12 text-light">
                        
                            <p><a style="color: #3b5998;" href="#!" role="button">
                                <i class="fab fa-facebook-f fa-lg"></i>
                            </a>
                            </p>
                        
                            <a
                                class="btn btn-link btn-floating btn-lg text-light m-1"
                                href="#!"
                                role="button"
                                data-mdb-ripple-color="dark"
                                ><i class="fab fa-twitter"></i
                            ></a>

                            <!-- Google -->
                            <a
                                class="btn btn-link btn-floating btn-lg text-light m-1"
                                href="#!"
                                role="button"
                                data-mdb-ripple-color="dark"
                                ><i class="fab fa-google"></i
                            ></a>

                            <!-- Instagram -->
                            <a
                                class="btn btn-link btn-floating btn-lg text-light m-1"
                                href="#!"
                                role="button"
                                data-mdb-ripple-color="dark"
                                ><i class="fab fa-instagram"></i
                            ></a>

                            <!-- Linkedin -->
                            <a
                                class="btn btn-link btn-floating btn-lg text-light m-1"
                                href="#!"
                                role="button"
                                data-mdb-ripple-color="dark"
                                ><i class="fab fa-linkedin"></i
                            ></a>
                            
                    </div>
                    </div>
                    
            </div>
            <div class="row">
            <p class="text-light text-center">© 2022 Nanaimo Makers. All rights reserved.</p></div>
        
    </footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LocalBusinessDirectory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  
    <%= javascript_importmap_tags %>

     <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet">
   
   <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/1980/1980788.png">
  </head>

  <body>
    <nav class="navbar navbar-dark navbar-expand bg-dark justify-content-between ">
  <a class="navbar-brand" href="/">Nanaimo Makers</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
       
        
  <% if user_signed_in? %>
  
    <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#>" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">
            Businesses
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="<%= root_path %>">View All Businesses</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="<%= new_business_path %>">Add New Business</a></li>
          </ul>
    </li>


    <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">
            Markets
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="<%= markets_path %>">Upcoming Markets</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="<%= new_market_path %>">Add Upcoming Event</a></li>
          </ul>
    </li>

       <%=  link_to "Businesses", root_path, class: "dropdown-menu" %>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">
            Classifieds
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="<%= classifieds_path %>">View Classified Ads</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="<%= new_classified_path %>">Add Classified Ad</a></li>
          </ul>
    </li>
        <%= button_to "Logout", session_path, method: :delete,
            data: {confirm: "are you sure you want to log out?"}, class: 'btn btn-default nav-link'%>
 

<span class="text-white nav-link" > 👋 Hey, <%= current_user.first_name%> </span>
  
   
   
 
  
  <% else %>
        <%= link_to "Home", root_path, class: "nav-item nav-link" %>
        <%= link_to "Upcoming Markets", markets_path, class: "nav-item nav-link" %>
        <%=  link_to "Classifieds", classifieds_path, class: "nav-item nav-link" %>
        <%= link_to "Login", new_session_path, class: "nav-item nav-link" %> 
        <%= link_to "Sign Up", new_user_path, class: "nav-item nav-link" %>
    <% end %>

  
  </div>
    </ul>
  </div>
</nav>
  <% if notice %>
    <%= render "layouts/alerts" %>
  <% end %>

    <%= yield %>
    <%= render "layouts/footer" %>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>